version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-1.10
      - test-1.11
      - test-1.12

_test-body: &test-body
  working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
  steps:
    - checkout
    - run: go get -v -t -d ./...
    - run: go test -v ./...

jobs:
  test-1.10:
    <<: *test-body
    docker:
      - image: circleci/golang:1.10
  test-1.11:
    <<: *test-body
    docker:
      - image: circleci/golang:1.11
  test-1.12:
    <<: *test-body
    docker:
      - image: circleci/golang:1.12
